/** biome-ignore-all lint/nursery/noPlaywrightWaitForSelector: simpler than locator chains */
/** biome-ignore-all lint/nursery/noPlaywrightWaitForTimeout: needed for debounced state save */
/** biome-ignore-all lint/performance/useTopLevelRegex: inline regex in test assertions */
/* oxlint-disable unicorn/no-await-expression-member */
import type { Page } from '@playwright/test'
import { expect, test } from '@playwright/test'
const TREE = 'nav[aria-label="File tree"]'
const waitTree = async (page: Page) => {
  await page.goto('/')
  await page.waitForSelector(TREE)
}
const openContextMenu = async (page: Page, selector: string) => {
  await page.locator(selector).first().click({ button: 'right' })
  await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
}
const openFile = async (page: Page, id: string) => {
  await page.locator(`button[data-item-id="${id}"]`).click()
  await page.waitForSelector('.dv-tab', { timeout: 10_000 })
}
const pinFile = async (page: Page, id: string) => {
  await page.locator(`button[data-item-id="${id}"]`).dblclick()
  await page.waitForSelector('.dv-tab', { timeout: 10_000 })
}
test.describe('tree basics', () => {
  test('page loads with default repo tree', async ({ page }) => {
    await waitTree(page)
    const tree = page.locator(TREE)
    await expect(tree).toBeVisible()
    expect(await tree.locator('button').count()).toBeGreaterThan(0)
  })
  test('clicking a file opens a tab with monaco editor', async ({ page }) => {
    await waitTree(page)
    await openFile(page, 'package.json')
    await expect(page.locator('.dv-tab').first()).toBeVisible()
    await page.waitForSelector('.monaco-editor', { timeout: 10_000 })
    await expect(page.locator('.monaco-editor').first()).toBeVisible()
  })
  test('double-click file pins tab', async ({ page }) => {
    await waitTree(page)
    await pinFile(page, '.gitignore')
    await expect(page.locator('.dv-tab').first()).toBeVisible()
  })
  test('single click opens preview, second single click replaces it', async ({ page }) => {
    await waitTree(page)
    await openFile(page, 'package.json')
    const tabsBefore = await page.locator('.dv-tab').count()
    await page.locator('button[data-item-id="turbo.json"]').click()
    await page.waitForTimeout(500)
    expect(await page.locator('.dv-tab').count()).toBeLessThanOrEqual(tabsBefore)
  })
  test('collapse all collapses expanded folders', async ({ page }) => {
    await waitTree(page)
    const nestedFile = page.locator('button[data-item-id="apps/web/package.json"]')
    await expect(nestedFile).toBeVisible({ timeout: 5000 })
    await page.locator('button[title="Collapse All"]').click()
    await expect(nestedFile).not.toBeVisible({ timeout: 3000 })
  })
  test('expand all after collapse restores folders', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[title="Collapse All"]').click()
    const nestedFile = page.locator('button[data-item-id="apps/web/package.json"]')
    await expect(nestedFile).not.toBeVisible({ timeout: 3000 })
    await page.locator('button[title="Expand All"]').click()
    await expect(nestedFile).toBeVisible({ timeout: 5000 })
  })
  test('folder click expands and collapses', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[title="Collapse All"]').click()
    await page.waitForTimeout(300)
    const folder = page.locator('button[data-item-id="apps"]').first()
    await folder.click()
    await page.waitForTimeout(300)
    const child = page.locator('button[data-item-id="apps/web/package.json"]')
    await expect(child).toBeVisible({ timeout: 5000 })
    await folder.click()
    await page.waitForTimeout(300)
    await expect(child).not.toBeVisible({ timeout: 3000 })
  })
  test('keyboard arrow navigation in tree', async ({ page }) => {
    await waitTree(page)
    const first = page.locator(`${TREE} [role=treeitem]`).first()
    await first.focus()
    await page.keyboard.press('ArrowDown')
    const second = page.locator(`${TREE} [role=treeitem]`).nth(1)
    await expect(second).toBeFocused({ timeout: 3000 })
  })
})
test.describe('tabs', () => {
  test('tab close button removes tab', async ({ page }) => {
    await waitTree(page)
    await openFile(page, '.gitignore')
    const tabCount = await page.locator('.dv-tab').count()
    expect(tabCount).toBeGreaterThan(0)
    const tab = page.locator('.dv-tab').first()
    await tab.hover()
    await tab.locator('svg.lucide-x').click()
    await page.waitForTimeout(300)
    expect(await page.locator('.dv-tab').count()).toBeLessThan(tabCount)
  })
  test('tab context menu shows Close, Close Others, Pin, Split Right', async ({ page }) => {
    await waitTree(page)
    await openFile(page, 'package.json')
    await page.locator('.dv-tab').first().click({ button: 'right' })
    await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
    await expect(page.locator('[role="menuitem"]:has-text("Close ⌥W")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Close Others")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Pin")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Split Right")')).toBeVisible()
  })
  test('Close Others closes other tabs', async ({ page }) => {
    await waitTree(page)
    await pinFile(page, 'package.json')
    await pinFile(page, '.gitignore')
    await pinFile(page, 'turbo.json')
    const tabCount = await page.locator('.dv-tab').count()
    expect(tabCount).toBeGreaterThanOrEqual(3)
    await page.locator('.dv-tab').first().click({ button: 'right' })
    await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
    await page.locator('[role="menuitem"]:has-text("Close Others")').click()
    await page.waitForTimeout(500)
    expect(await page.locator('.dv-tab').count()).toBeLessThan(tabCount)
  })
  test('Close All closes all non-pinned tabs', async ({ page }) => {
    await waitTree(page)
    await pinFile(page, 'package.json')
    await pinFile(page, '.gitignore')
    expect(await page.locator('.dv-tab').count()).toBeGreaterThanOrEqual(2)
    await page.locator('.dv-tab').first().click({ button: 'right' })
    await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
    await page.locator('[role="menuitem"]:has-text("Close All")').click()
    await page.waitForTimeout(500)
    expect(await page.locator('.dv-tab').count()).toBe(0)
  })
  test('pin tab shows pin icon and survives Close All', async ({ page }) => {
    await waitTree(page)
    await pinFile(page, 'package.json')
    const tab = page.locator('.dv-tab').first()
    await tab.click({ button: 'right' })
    await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
    await page.locator('[role="menuitem"]:has-text("Pin")').click()
    await tab.hover()
    await expect(tab.locator('svg.lucide-pin')).toBeVisible({ timeout: 3000 })
    await page.keyboard.press('Meta+Shift+w')
    await page.waitForTimeout(500)
    expect(await page.locator('.dv-tab').count()).toBeGreaterThanOrEqual(1)
  })
  test('Split Right creates second panel group', async ({ page }) => {
    await waitTree(page)
    await openFile(page, 'package.json')
    await page.locator('.dv-tab').first().click({ button: 'right' })
    await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
    await page.locator('[role="menuitem"]:has-text("Split Right")').click()
    await page.waitForTimeout(500)
    expect(await page.locator('.dv-tab').count()).toBeGreaterThanOrEqual(2)
  })
  test('middle-click closes tab', async ({ page }) => {
    await waitTree(page)
    await pinFile(page, 'package.json')
    const tabCount = await page.locator('.dv-tab').count()
    await page.locator('.dv-tab').first().click({ button: 'middle' })
    await page.waitForTimeout(300)
    expect(await page.locator('.dv-tab').count()).toBeLessThan(tabCount)
  })
})
test.describe('theme', () => {
  test('theme toggle switches between light and dark', async ({ page }) => {
    await page.goto('/')
    await page.waitForSelector('html.dark')
    const themeButton = page.locator('button:has(svg.lucide-sun), button:has(svg.lucide-moon)')
    await themeButton.click()
    await expect(page.locator('html.light')).toBeVisible({ timeout: 2000 })
    await themeButton.click()
    await expect(page.locator('html.dark')).toBeVisible({ timeout: 2000 })
  })
})
test.describe('keyboard shortcuts', () => {
  test('Cmd+B toggles sidebar', async ({ page }) => {
    await waitTree(page)
    await expect(page.locator(TREE)).toBeVisible()
    await page.keyboard.press('Meta+b')
    await expect(page.locator(TREE)).not.toBeVisible({ timeout: 3000 })
    await page.keyboard.press('Meta+b')
    await expect(page.locator(TREE)).toBeVisible({ timeout: 3000 })
  })
  test('Cmd+P opens quick open dialog', async ({ page }) => {
    await waitTree(page)
    await page.keyboard.press('Meta+p')
    await expect(page.locator('input[placeholder="Search files..."]')).toBeVisible({ timeout: 3000 })
  })
  test('quick open search filters files', async ({ page }) => {
    await waitTree(page)
    await page.keyboard.press('Meta+p')
    const input = page.locator('input[placeholder="Search files..."]')
    await input.fill('package')
    await page.waitForTimeout(300)
    expect(await page.locator('[cmdk-item]').count()).toBeGreaterThan(0)
  })
  test('quick open selecting file opens it', async ({ page }) => {
    await waitTree(page)
    await page.keyboard.press('Meta+p')
    const input = page.locator('input[placeholder="Search files..."]')
    await input.fill('turbo.json')
    await page.waitForTimeout(300)
    await input.press('Enter')
    await page.waitForSelector('.dv-tab', { timeout: 10_000 })
    await expect(page.locator('.dv-tab').first()).toBeVisible()
  })
  test('Cmd+Shift+T reopens last closed tab', async ({ page }) => {
    await waitTree(page)
    await pinFile(page, 'package.json')
    const tabsBefore = await page.locator('.dv-tab').count()
    const tab = page.locator('.dv-tab').first()
    await tab.hover()
    await tab.locator('svg.lucide-x').click()
    await page.waitForTimeout(300)
    expect(await page.locator('.dv-tab').count()).toBeLessThan(tabsBefore)
    await page.keyboard.press('Meta+Shift+t')
    await page.waitForSelector('.dv-tab', { timeout: 10_000 })
    expect(await page.locator('.dv-tab').count()).toBeGreaterThan(0)
  })
  test('Cmd+= zooms in, Cmd+- zooms out, Cmd+0 resets', async ({ page }) => {
    await waitTree(page)
    await openFile(page, 'package.json')
    await page.waitForSelector('.monaco-editor', { timeout: 10_000 })
    await page.keyboard.press('Meta+=')
    await page.waitForTimeout(200)
    await page.keyboard.press('Meta+-')
    await page.waitForTimeout(200)
    await page.keyboard.press('Meta+0')
    await page.waitForTimeout(200)
    await expect(page.locator('.monaco-editor').first()).toBeVisible()
  })
  test('Alt+W closes active tab', async ({ page }) => {
    await waitTree(page)
    await pinFile(page, 'package.json')
    const tabCount = await page.locator('.dv-tab').count()
    await page.keyboard.press('Alt+w')
    await page.waitForTimeout(300)
    expect(await page.locator('.dv-tab').count()).toBeLessThan(tabCount)
  })
  test('Alt+E cycles to next tab', async ({ page }) => {
    await waitTree(page)
    await pinFile(page, 'package.json')
    await pinFile(page, '.gitignore')
    await page.keyboard.press('Alt+e')
    await page.waitForTimeout(300)
    await expect(page.locator('.dv-tab').first()).toBeVisible()
  })
})
test.describe('tree header icons', () => {
  test('all action icons visible when fileActions provided', async ({ page }) => {
    await waitTree(page)
    await expect(page.locator('button[title="New File"]')).toBeVisible()
    await expect(page.locator('button[title="New Folder"]')).toBeVisible()
    await expect(page.locator('button[title="Upload"]')).toBeVisible()
    await expect(page.locator('button[title="Collapse All"]')).toBeVisible()
  })
})
test.describe('file context menu', () => {
  test('shows Rename, Delete, Download, Copy Path', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="package.json"]')
    await expect(page.locator('[role="menuitem"]:has-text("Rename")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Delete")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Download")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Copy Path")')).toBeVisible()
  })
  test('Delete shows toast', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="package.json"]')
    await page.locator('[role="menuitem"]:has-text("Delete")').click()
    await expect(page.locator('text=Demo: would delete 1 item')).toBeVisible({ timeout: 5000 })
  })
  test('Download shows toast', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="package.json"]')
    await page.locator('[role="menuitem"]:has-text("Download")').click()
    await expect(page.locator('text=Downloaded')).toBeVisible({ timeout: 10_000 })
  })
  test('Rename shows inline input and submits on Enter', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="package.json"]')
    await page.locator('[role="menuitem"]:has-text("Rename")').click()
    const input = page.locator('input[type="text"]').first()
    await expect(input).toBeVisible({ timeout: 3000 })
    await expect(input).toHaveValue('package.json')
    await input.fill('renamed.json')
    await input.press('Enter')
    await expect(page.locator('text=Demo: would rename')).toBeVisible({ timeout: 5000 })
  })
  test('Rename cancels on Escape', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="package.json"]')
    await page.locator('[role="menuitem"]:has-text("Rename")').click()
    const input = page.locator('input[type="text"]').first()
    await expect(input).toBeVisible({ timeout: 3000 })
    await input.press('Escape')
    await expect(input).not.toBeVisible({ timeout: 3000 })
  })
  test('Rename selects name without extension', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="package.json"]')
    await page.locator('[role="menuitem"]:has-text("Rename")').click()
    const input = page.locator('input[type="text"]').first()
    await expect(input).toBeVisible({ timeout: 3000 })
    const selStart = await input.evaluate((el: HTMLInputElement) => el.selectionStart)
    const selEnd = await input.evaluate((el: HTMLInputElement) => el.selectionEnd)
    expect(selStart).toBe(0)
    expect(selEnd).toBe(7)
  })
  test('Copy Path copies to clipboard', async ({ browser }) => {
    const context = await browser.newContext({ permissions: ['clipboard-read', 'clipboard-write'] })
    const page = await context.newPage()
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="package.json"]')
    await page.locator('[role="menuitem"]:has-text("Copy Path")').click()
    await expect(page.locator('text=Copied to clipboard')).toBeVisible({ timeout: 5000 })
    await context.close()
  })
})
test.describe('folder context menu', () => {
  test('shows New File, New Folder, Upload, Rename, Delete, Copy Path', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="packages"]')
    await expect(page.locator('[role="menuitem"]:has-text("New File")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("New Folder")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Upload")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Rename")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Delete")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Download")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Copy Path")')).toBeVisible()
  })
  test('Download folder shows toast', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="packages"]')
    await page.locator('[role="menuitem"]:has-text("Download")').click()
    await expect(page.locator('text=Downloaded')).toBeVisible({ timeout: 10_000 })
  })
  test('New File shows inline input inside folder', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="packages"]')
    await page.locator('[role="menuitem"]:has-text("New File")').click()
    await expect(page.locator('input[placeholder="filename"]')).toBeVisible({ timeout: 3000 })
  })
  test('New File inside folder → submit → toast shows parent path', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="packages"]')
    await page.locator('[role="menuitem"]:has-text("New File")').click()
    const input = page.locator('input[placeholder="filename"]')
    await input.fill('helper.ts')
    await input.press('Enter')
    await expect(page.locator('text=Demo: would create file "helper.ts" in packages')).toBeVisible({ timeout: 5000 })
  })
  test('New Folder shows inline input inside folder', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="packages"]')
    await page.locator('[role="menuitem"]:has-text("New Folder")').click()
    await expect(page.locator('input[placeholder="folder name"]')).toBeVisible({ timeout: 3000 })
  })
  test('Delete shows toast', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="packages"]')
    await page.locator('[role="menuitem"]:has-text("Delete")').click()
    await expect(page.locator('text=Demo: would delete 1 item')).toBeVisible({ timeout: 5000 })
  })
  test('Rename shows inline input and submits on Enter', async ({ page }) => {
    await waitTree(page)
    await openContextMenu(page, 'button[data-item-id="packages"]')
    await page.locator('[role="menuitem"]:has-text("Rename")').click()
    const input = page.locator('input[type="text"]').first()
    await expect(input).toBeVisible({ timeout: 3000 })
    await input.fill('renamed-folder')
    await input.press('Enter')
    await expect(page.locator('text=Demo: would rename')).toBeVisible({ timeout: 5000 })
  })
})
test.describe('empty space context menu', () => {
  test('right-click empty area shows New File, New Folder, Upload', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[title="Collapse All"]').click()
    await page.waitForTimeout(300)
    const treeArea = page.locator(TREE).locator('..')
    const box = await treeArea.boundingBox()
    if (!box) throw new Error('no tree area')
    await treeArea.click({ button: 'right', position: { x: 10, y: box.height - 20 } })
    await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
    await expect(page.locator('[role="menuitem"]:has-text("New File")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("New Folder")')).toBeVisible()
    await expect(page.locator('[role="menuitem"]:has-text("Upload")')).toBeVisible()
  })
})
test.describe('inline input', () => {
  test('new file header → Enter → create file toast', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[title="New File"]').click()
    const input = page.locator('input[placeholder="filename"]')
    await input.fill('test.txt')
    await input.press('Enter')
    await expect(page.locator('text=Demo: would create file "test.txt"')).toBeVisible({ timeout: 5000 })
  })
  test('new folder header → Enter → create folder toast', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[title="New Folder"]').click()
    const input = page.locator('input[placeholder="folder name"]')
    await input.fill('new-dir')
    await input.press('Enter')
    await expect(page.locator('text=Demo: would create folder "new-dir"')).toBeVisible({ timeout: 5000 })
  })
  test('Escape cancels inline input', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[title="New File"]').click()
    const input = page.locator('input[placeholder="filename"]')
    await expect(input).toBeVisible({ timeout: 3000 })
    await input.press('Escape')
    await expect(input).not.toBeVisible({ timeout: 3000 })
  })
  test('blur with text submits', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[title="New File"]').click()
    const input = page.locator('input[placeholder="filename"]')
    await input.fill('blurred.ts')
    await page.locator('button[data-item-id="package.json"]').click()
    await expect(page.locator('text=Demo: would create file "blurred.ts"')).toBeVisible({ timeout: 5000 })
  })
  test('blur with empty text cancels', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[title="New File"]').click()
    const input = page.locator('input[placeholder="filename"]')
    await expect(input).toBeVisible({ timeout: 3000 })
    await page.locator('button[data-item-id="package.json"]').click()
    await expect(input).not.toBeVisible({ timeout: 3000 })
  })
})
test.describe('multi-select', () => {
  test('cmd-click highlights multiple files', async ({ page }) => {
    await waitTree(page)
    const first = page.locator('button[data-item-id="package.json"]')
    const second = page.locator('button[data-item-id=".gitignore"]')
    await first.click()
    await second.click({ modifiers: ['Meta'] })
    await expect(first).toHaveClass(/bg-accent/u)
    await expect(second).toHaveClass(/bg-accent/u)
  })
  test('cmd-click toggles off already selected item', async ({ page }) => {
    await waitTree(page)
    const first = page.locator('button[data-item-id="package.json"]')
    const second = page.locator('button[data-item-id=".gitignore"]')
    await first.click()
    await second.click({ modifiers: ['Meta'] })
    await expect(second).toHaveClass(/bg-accent/u)
    await first.click({ modifiers: ['Meta'] })
    await expect(first).not.toHaveClass(/ bg-accent/u)
    await expect(second).toHaveClass(/bg-accent/u)
  })
  test('shift-click range selects files between anchors', async ({ page }) => {
    await waitTree(page)
    const items = page.locator(`${TREE} button[data-item-id]`)
    const first = items.nth(0)
    const third = items.nth(2)
    await first.click()
    await third.click({ modifiers: ['Shift'] })
    const second = items.nth(1)
    await expect(first).toHaveClass(/bg-accent/u)
    await expect(second).toHaveClass(/bg-accent/u)
    await expect(third).toHaveClass(/bg-accent/u)
  })
  test('normal click clears multi-select', async ({ page }) => {
    await waitTree(page)
    const first = page.locator('button[data-item-id="package.json"]')
    const second = page.locator('button[data-item-id=".gitignore"]')
    await first.click()
    await second.click({ modifiers: ['Meta'] })
    await expect(first).toHaveClass(/bg-accent/u)
    await expect(second).toHaveClass(/bg-accent/u)
    const third = page.locator('button[data-item-id="turbo.json"]')
    await third.click()
    await expect(first).not.toHaveClass(/ bg-accent/u)
    await expect(second).not.toHaveClass(/ bg-accent/u)
  })
  test('delete shows count in context menu', async ({ page }) => {
    await waitTree(page)
    const first = page.locator('button[data-item-id="package.json"]')
    const second = page.locator('button[data-item-id=".gitignore"]')
    await first.click()
    await second.click({ modifiers: ['Meta'] })
    await second.click({ button: 'right' })
    await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
    await expect(page.locator('[role="menuitem"]:has-text("Delete (2)")')).toBeVisible()
  })
  test('batch delete toast shows correct count', async ({ page }) => {
    await waitTree(page)
    const first = page.locator('button[data-item-id="package.json"]')
    const second = page.locator('button[data-item-id=".gitignore"]')
    await first.click()
    await second.click({ modifiers: ['Meta'] })
    await second.click({ button: 'right' })
    await page.waitForSelector('[role="menuitem"]', { timeout: 5000 })
    await page.locator('[role="menuitem"]:has-text("Delete (2)")').click()
    await expect(page.locator('text=Demo: would delete 2 item')).toBeVisible({ timeout: 5000 })
  })
})
test.describe('status bar', () => {
  test('shows cursor position and language', async ({ page }) => {
    await waitTree(page)
    await openFile(page, 'package.json')
    await page.waitForSelector('.monaco-editor', { timeout: 10_000 })
    await page.waitForTimeout(500)
    const statusBar = page
      .locator('div')
      .filter({ hasText: /Ln \d+, Col \d+/u })
      .last()
    await expect(statusBar).toBeVisible({ timeout: 5000 })
  })
})
test.describe('sidebar', () => {
  test('sidebar toggle button works', async ({ page }) => {
    await waitTree(page)
    await expect(page.locator(TREE)).toBeVisible()
    await page.locator('svg.lucide-panel-left').click()
    await expect(page.locator(TREE)).not.toBeVisible({ timeout: 3000 })
    await page.locator('svg.lucide-panel-left').click()
    await expect(page.locator(TREE)).toBeVisible({ timeout: 3000 })
  })
})
test.describe('activity log', () => {
  test('virtual file exists in tree', async ({ page }) => {
    await waitTree(page)
    await expect(page.locator(`${TREE} button`).filter({ hasText: 'Activity' })).toBeVisible({ timeout: 5000 })
  })
  test('clicking opens it as tab', async ({ page }) => {
    await waitTree(page)
    await page.locator(`${TREE} button`).filter({ hasText: 'Activity' }).click()
    await page.waitForSelector('.dv-tab', { timeout: 10_000 })
    await expect(page.locator('.dv-tab').filter({ hasText: 'Activity' })).toBeVisible()
  })
})
test.describe('breadcrumb', () => {
  test('shows path segments when nested file open', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[data-item-id="apps/web/package.json"]').click()
    await page.waitForSelector('.monaco-editor', { timeout: 10_000 })
    await expect(page.locator('nav[aria-label="breadcrumb"]')).toBeVisible({ timeout: 5000 })
  })
  test('breadcrumb segment click opens picker dropdown', async ({ page }) => {
    await waitTree(page)
    await page.locator('button[data-item-id="apps/web/package.json"]').click()
    await page.waitForSelector('.monaco-editor', { timeout: 10_000 })
    await page.waitForTimeout(500)
    const segment = page.locator('nav[aria-label="breadcrumb"] button').first()
    await segment.click()
    await page.waitForTimeout(300)
    await expect(page.locator('[data-slot="popover-content"]')).toBeVisible({ timeout: 3000 })
  })
})
