/** biome-ignore-all lint/nursery/noPlaywrightWaitForSelector: simpler than locator chains */
/** biome-ignore-all lint/nursery/noPlaywrightWaitForTimeout: needed for debounced state save */
/** biome-ignore-all lint/suspicious/noSkippedTests: GitHub API rate limit */
/* oxlint-disable unicorn/no-await-expression-member */
import { expect, test } from '@playwright/test'
test.describe('idecn demo', () => {
  test('page loads with default repo tree', async ({ page }) => {
    await page.goto('/')
    await page.waitForSelector('nav[aria-label="File tree"]')
    const tree = page.locator('nav[aria-label="File tree"]')
    await expect(tree).toBeVisible()
    const items = tree.locator('button')
    expect(await items.count()).toBeGreaterThan(0)
  })
  test('clicking a file opens a tab with content', async ({ page }) => {
    await page.goto('/')
    await page.waitForSelector('nav[aria-label="File tree"]')
    const file = page.locator('nav[aria-label="File tree"] button:has-text("package.json")')
    await file.click()
    await page.waitForSelector('.dv-tab', { timeout: 10_000 })
    await expect(page.locator('.dv-tab').first()).toBeVisible()
    await page.waitForSelector('.monaco-editor', { timeout: 10_000 })
    await expect(page.locator('.monaco-editor').first()).toBeVisible()
  })
  test('theme toggle switches between light and dark', async ({ page }) => {
    await page.goto('/')
    await page.waitForSelector('html.dark')
    const themeButton = page.locator('button:has(svg.lucide-sun), button:has(svg.lucide-moon)')
    await themeButton.click()
    await expect(page.locator('html.light')).toBeVisible({ timeout: 2000 })
    await themeButton.click()
    await expect(page.locator('html.dark')).toBeVisible({ timeout: 2000 })
  })
  test('URL hash updates when opening a file', async ({ page }) => {
    await page.goto('/')
    await page.waitForSelector('nav[aria-label="File tree"]')
    const file = page.locator('nav[aria-label="File tree"] button:has-text("package.json")')
    await file.click()
    await page.waitForTimeout(500)
    expect(page.url()).toContain('#')
  })
  test('state persists across page reload', async ({ page }) => {
    await page.goto('/')
    await page.waitForSelector('nav[aria-label="File tree"]')
    const file = page.locator('nav[aria-label="File tree"] button:has-text(".gitignore")')
    await file.click()
    await page.waitForSelector('.dv-tab', { timeout: 10_000 })
    await page.waitForTimeout(1000)
    const hashBefore = new URL(page.url()).hash
    expect(hashBefore.length).toBeGreaterThan(1)
    await page.reload()
    await page.waitForSelector('.dv-tab', { timeout: 15_000 })
    await expect(page.locator('.dv-tab').first()).toBeVisible()
  })
  test.skip('search input changes repo (requires GitHub API)', async ({ page }) => {
    await page.goto('/')
    await page.waitForSelector('nav[aria-label="File tree"]')
    const input = page.locator('input[type="search"]')
    await input.fill('vercel/next.js')
    await input.press('Enter')
    await page.waitForSelector('text=Loading...', { timeout: 3000 })
    await page.waitForSelector('nav[aria-label="File tree"] button', { timeout: 15_000 })
    expect(await page.locator('nav[aria-label="File tree"] button').count()).toBeGreaterThan(0)
  })
  test('tab close button works', async ({ page }) => {
    await page.goto('/')
    await page.waitForSelector('nav[aria-label="File tree"]')
    const file = page.locator('nav[aria-label="File tree"] button:has-text(".gitignore")')
    await file.click()
    await page.waitForSelector('.dv-tab', { timeout: 10_000 })
    const tabCount = await page.locator('.dv-tab').count()
    expect(tabCount).toBeGreaterThan(0)
    const tab = page.locator('.dv-tab').first()
    await tab.hover()
    const closeBtn = tab.locator('svg.lucide-x')
    await closeBtn.click()
    await page.waitForTimeout(300)
    expect(await page.locator('.dv-tab').count()).toBeLessThan(tabCount)
  })
})
